/*Layout é o modelo fixo da nossa página*/
/*Aqui faz a importação de fontes e estilos*/
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logosky from "./src/logoSky.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/*Titulo e aba do navegador*/
export const metadata: Metadata = {
  title: "Projeto Skyline",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  
  
  /*Onde o códgio do layout começa*/
  return (
    <html lang="pt-BR">
      <head>
        <link rel="icon" href="/imagens/logoSkyAbaNavegador.svg" />
      </head>
      <body className="flex flex-col">
      {/*Header*/}

      <header className="w-full h-[8vh] bg-[var(--indigoEscuro)] flex justify-between items-center">
        <img
          src="/imagens/logoSkyy.png"
          alt="Logo Skyline"
          className="h-full"
        />
        <img src="/imagens/menuIcon.svg" alt="Menu icon" className="h-[5vh]" />
      </header>
      <section className="bg-[var(--indigoMaisEscuro)] w-screen h-[92vh] flex">
      {/*----------------O conteudo váriavel começa aqui(GRID)--------------*/}
      {children}
      </section>
      </body>
    </html>
  );
}
